# Generated by Django 3.2.13 on 2023-02-19 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_review_description_alter_review_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='description',
        ),
    ]
