# Generated by Django 3.2.13 on 2023-02-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_review_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='description',
            field=models.CharField(default='desc', max_length=500),
            preserve_default=False,
        ),
    ]
