# Generated by Django 3.1.5 on 2022-08-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='categories/'),
        ),
        migrations.AddField(
            model_name='category',
            name='subtitle',
            field=models.CharField(default='subtitle', max_length=50),
        ),
    ]
