# Generated by Django 3.2.13 on 2023-02-01 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='greenieuser',
            name='is_admin',
        ),
    ]
