# Generated by Django 3.2.13 on 2023-02-04 14:17

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_greenieuser_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeleveryAddress',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ', editable=False, length=8, max_length=8, prefix='', primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=400)),
                ('pincode', models.CharField(max_length=6)),
                ('phone', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='user.greenieuser')),
            ],
            options={
                'db_table': 'delevery_address',
            },
        ),
    ]
