# Generated by Django 3.2.13 on 2023-02-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_deleveryaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='deleveryaddress',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='deleveryaddress',
            name='type',
            field=models.CharField(choices=[('HOME', 'HOME'), ('WORK', 'WORK')], default='HOME', max_length=15),
        ),
    ]
