# Generated by Django 3.2.13 on 2023-02-04 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20230204_1441'),
        ('order', '0003_auto_20230204_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.deleveryaddress'),
        ),
    ]
