# Generated by Django 3.2.13 on 2023-02-05 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_contact_id'),
        ('product', '0003_auto_20230202_1950'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0006_auto_20230205_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='product.product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='user.greenieuser'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='user.deleveryaddress'),
        ),
        migrations.AlterField(
            model_name='txn',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='txns', to='order.order'),
        ),
        migrations.AlterField(
            model_name='txn',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='txns', to='product.product'),
        ),
        migrations.AlterField(
            model_name='txn',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='txns', to='order.purchase'),
        ),
        migrations.AlterField(
            model_name='txn',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='txns', to=settings.AUTH_USER_MODEL),
        ),
    ]
